spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: ${db.local.url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${db.local.username}
    password: ${db.local.password}