app:
  auth:
    token:
      secret-key: "starter-valley-jwt-secret-key"
      refresh-key: "starter-valley-jwt-refresh-key"
      expiry:
        access-token: 3600000 # 1000 * 60 * 60 = 1 hr
        refresh-token: 604800000 # 1000 * 60 * 60 * 24 * 7 = 1 week
  oauth2:
    client:
      github:
        access-token-uri: "https://github.com/login/oauth/access_token"
        user-data-uri: "https://api.github.com/user"
        user-email-uri: "https://api.github.com/user/emails"


cloud:
  aws:
    s3:
      bucket: starter-valley-bucket
    credentials:
      accessKey: AKIAQBVIBHZW7VNPN452
      secretKey: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false


open-api:
  holiday-key: P4EeudriVjVdF6RB5PCk1LPkP%2FpkwHe2iXAGL2FD3kwGSH%2BHowGdPEqXD4u05SCAIPsBugdpKipsOQ5OfVTFWw%3D%3D

slack:
  token: xoxb-4175653470198-4623780411009-EtLdImWZxifs3n3SvzkNUFgU
  channel:
    monitor: 'starter-valley'
---
spring:
  config:
    activate:
      on-profile: prod, prod1, prod2

app:
  oauth2:
    client:
      github:
        client-id: e731c1d25d4cc09e1cb5
        client-secret: f29e579c65c8ac58cbe7317295adfe619dd876c4